[project]
name = "alphad-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "datasets>=4.3.0",
    "torch>=2.10.0",
    "transformers>=4.57.6",
    "trl>=0.24.0",
    "unsloth>=2026.2.1",
]
