[project]
name = "alphad-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "datasets>=4.5.0",
    "torch>=2.9.1",
    "transformers>=4.57.6",
    "trl[vllm]>=0.23.1",
    "vllm>=0.15.1",
]